// -*- C++ -*-
//===----------------------------------------------------------------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

export namespace std {
  using std::clock_t _LIBCPP_USING_IF_EXISTS;
  using std::size_t _LIBCPP_USING_IF_EXISTS;
  using std::time_t _LIBCPP_USING_IF_EXISTS;

  using std::timespec _LIBCPP_USING_IF_EXISTS;
  using std::tm _LIBCPP_USING_IF_EXISTS;

  using std::asctime _LIBCPP_USING_IF_EXISTS;
  using std::clock _LIBCPP_USING_IF_EXISTS;

  using std::strftime _LIBCPP_USING_IF_EXISTS;

} // namespace std
